Database/procedures
bmarcu13/ProiectBD pull request #5
Opened 2023-12-15 20:02 UTC by RaresMrc

Adding almost all procedures from the third module together with a few utility functions.

2023-12-15 20:05 UTC, RaresMrc reviewed
### I'm just **testing** the feature, **don't mind** this comment.

2023-12-16 08:56 UTC, bmarcu13 requested changes
Please make the requested changes.

2023-12-16 08:56 UTC, bmarcu13 commented on database/procedures/get_appointed_patients.sql
Procedures should be kept in subdirectories representing the functionality module they belong to. Please create the needed subdirectory(ies) and move them accordingly.

2023-12-16 08:56 UTC, bmarcu13 commented on database/procedures/get_medic_name.sql
We should keep helper functions for procedures in a separate folder. e.g. `database/helper_functions`

2023-12-17 11:35 UTC, bmarcu13 approved these changes

2023-12-17 14:01 UTC, merged